language: go
go:
- 1.16
- tip
before_install:
- go get github.com/axw/gocov/gocov
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- "./testing/coverage/coverall"
env:
  secure: 2f117zq6/xG7wvQjCzDVL/DuQB6O2Yf4O6Xarjv31lo+shqC+dQ6gpVrDjczShNWsihsg9gmCXU6q5kgy9UFluy/5Jf6zihYbtnuO4xo5vf85+cASo1aSNwxQHCCvf1TpdIdgNQgWf/S+y105D/ObQgbgjxTz8oedDIRFhFMzJWsIHIYLRjOuhJRqOvmaKvV/N9KYFIziMew+KRCHJOPhGaLGfIVfhBwqulYEWkXOD+mdYveTsUANTkF6/qtFnMp0pDBfGBrdo3SPTYFUwgp8hW4pH7/cE97eGpvQGW9FcdNo75aOV5Hy0fOXti6g9jrOeAb9quXBmoc2H4YMEt4gLLv2g3EQhu2fzckyti/IZ2w5zPvI7rSNNf40GkMEQbnDS71LQYR67bqHpunJ/4fkqSBGpHhEaXp5K4TsuCG6vlYXPUvQTyMkXFaJQNaGGq/PibR6Kh98bcvUU7ibrUgZOhFAJh4NyANM52pkS7XJsNDka5QGNmEeSjqzmuy0eslswNfbg5R1CweP9ZnqkkacRu4TGpqwybWK7H7MI01GOOOx+nRn7zburk0xyRTkUMiqbKGUo8f6PCYZrFY9ryH+JFt2SVbY8fPWngIdR21Jd+atv/cyfRVt7BfYGG7kBX85ffJx7AkmcWZr6s47gZGy3v9DcXjraSSK5W3uJaUz4M=
  global:
    secure: AK/gdyOEL/SQIlhN59adSCLEeDxA1PGIfPnUFtJouJGNIG1G17aFes+doYGW8EQotzRLput5QEAGge32xCF8P3AtfCDgJscNaLPWhfUyHEDdRxMggE9m+1ooVsHeuITcb3n3xzwodBvD0DHmbvXlVEWbX8v3PecPXowkPPOcZVJ29C8BtRBAb5qLcFlkmvzoUOQBQ3eAZ0L8WfUKCH0YqqKM4QYLfFb9lTCQWJZU9boIH9GWUuWoR9oSUTYBlS/AOfsFo+KsR3m4PZx4jCTEttPov+wa6b+RRzCrUTa6WW8fJfKgM4Af9vSsToRf785kyIzeVI8EqZQbPzBCXoa6WGI1aJxzhcbEtSe2iKZ01p5jzjT37UjDKy72+2NK1qTBHaUI1ST9JtKoWeB3tuqQ86XhpB68Q1/ZeyqM416cJu6n3ABVNps5GA+mTdA3PncwkX9rz3OTLC23hGjXHmh8+gHJhEGwidvYHphbSl2Ihq5CD7IOJofhL0gXGFpcQDNZX8IxtHdXLp0VyxBpfs6N2AuaIfxmaiEHq8RdeTXMR+9NVyfM0Bhm0SWlG4N9IRG/pdxPmlFnQIuqcsaGWvx1/MXUsjWpXCN/Bb80ItSJsPzWL4BxTaa4PqcZb2srX9TEvndp/iP1ppUq3S44Grzho/Y/Do5+u1R5269kj/oWGdg=
