language: go

go:
  - 1.16
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - ./testing/coverage/coverall

env:
  secure: "2f117zq6/xG7wvQjCzDVL/DuQB6O2Yf4O6Xarjv31lo+shqC+dQ6gpVrDjczShNWsihsg9gmCXU6q5kgy9UFluy/5Jf6zihYbtnuO4xo5vf85+cASo1aSNwxQHCCvf1TpdIdgNQgWf/S+y105D/ObQgbgjxTz8oedDIRFhFMzJWsIHIYLRjOuhJRqOvmaKvV/N9KYFIziMew+KRCHJOPhGaLGfIVfhBwqulYEWkXOD+mdYveTsUANTkF6/qtFnMp0pDBfGBrdo3SPTYFUwgp8hW4pH7/cE97eGpvQGW9FcdNo75aOV5Hy0fOXti6g9jrOeAb9quXBmoc2H4YMEt4gLLv2g3EQhu2fzckyti/IZ2w5zPvI7rSNNf40GkMEQbnDS71LQYR67bqHpunJ/4fkqSBGpHhEaXp5K4TsuCG6vlYXPUvQTyMkXFaJQNaGGq/PibR6Kh98bcvUU7ibrUgZOhFAJh4NyANM52pkS7XJsNDka5QGNmEeSjqzmuy0eslswNfbg5R1CweP9ZnqkkacRu4TGpqwybWK7H7MI01GOOOx+nRn7zburk0xyRTkUMiqbKGUo8f6PCYZrFY9ryH+JFt2SVbY8fPWngIdR21Jd+atv/cyfRVt7BfYGG7kBX85ffJx7AkmcWZr6s47gZGy3v9DcXjraSSK5W3uJaUz4M="